# Generated by Django 2.0.13 on 2019-05-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='friend_name',
            field=models.CharField(default='shark', max_length=20),
        ),
    ]
